version: '3.7'



services:

  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../src:/myfolder/backend/src
    ports:
      - 4000:4000


  my-database:
    image: mongo:5
    ports:
      - 27017:27017
    